### ISSUE TITLE
Problems compiling lib please help me

### ISSUE THREAD

**Issue by DurankGts** [Dirk-/NanoBLEFlashPrefs#5]
please helpe to solve this issue
Using board 'nano_33_iot' from platform in folder: C:\Users\Usuario\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11
Using core 'arduino' from platform in folder: C:\Users\Usuario\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11
Detecting libraries used...
"C:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_NANO_33_IOT -DARDUINO_ARCH_SAMD -DCRYSTALLESS -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8057 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino NANO 33 IoT\"" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS\\4.5.0/CMSIS/Include/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS-Atmel\\1.2.0/CMSIS/Device/ATMEL/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated-avr-comp" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\variants\\nano_33_iot" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\arduino-sketch-177033604A36BF84B4A8134C85488391\\sketch\\SmartLockSmith.ino.cpp" -o nul
Alternatives for Arduino_JSON.h: [Arduino_JSON@0.1.0]
ResolveLibrary(Arduino_JSON.h)
  -> candidates: [Arduino_JSON@0.1.0]
"C:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_NANO_33_IOT -DARDUINO_ARCH_SAMD -DCRYSTALLESS -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8057 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino NANO 33 IoT\"" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS\\4.5.0/CMSIS/Include/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS-Atmel\\1.2.0/CMSIS/Device/ATMEL/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated-avr-comp" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\variants\\nano_33_iot" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\Arduino_JSON\\src" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\arduino-sketch-177033604A36BF84B4A8134C85488391\\sketch\\SmartLockSmith.ino.cpp" -o nul
Alternatives for ArduinoBLE.h: [ArduinoBLE@1.2.1]
ResolveLibrary(ArduinoBLE.h)
  -> candidates: [ArduinoBLE@1.2.1]
"C:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_NANO_33_IOT -DARDUINO_ARCH_SAMD -DCRYSTALLESS -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8057 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino NANO 33 IoT\"" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS\\4.5.0/CMSIS/Include/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS-Atmel\\1.2.0/CMSIS/Device/ATMEL/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated-avr-comp" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\variants\\nano_33_iot" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\Arduino_JSON\\src" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\ArduinoBLE\\src" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\arduino-sketch-177033604A36BF84B4A8134C85488391\\sketch\\SmartLockSmith.ino.cpp" -o nul
Alternatives for NanoBLEFlashPrefs.h: [NanoBLEFlashPrefs@1.1.0]
ResolveLibrary(NanoBLEFlashPrefs.h)
  -> candidates: [NanoBLEFlashPrefs@1.1.0]
"C:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_NANO_33_IOT -DARDUINO_ARCH_SAMD -DCRYSTALLESS -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8057 -DUSBCON "-DUSB_MANUFACTURER=\"Arduino LLC\"" "-DUSB_PRODUCT=\"Arduino NANO 33 IoT\"" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS\\4.5.0/CMSIS/Include/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS-Atmel\\1.2.0/CMSIS/Device/ATMEL/" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino/api/deprecated-avr-comp" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\cores\\arduino" "-IC:\\Users\\Usuario\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\samd\\1.8.11\\variants\\nano_33_iot" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\Arduino_JSON\\src" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\ArduinoBLE\\src" "-IC:\\Users\\Usuario\\Documents\\Arduino\\libraries\\NanoBLEFlashPrefs\\src" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\arduino-sketch-177033604A36BF84B4A8134C85488391\\sketch\\SmartLockSmith.ino.cpp" -o nul
Alternatives for fds.h: []
ResolveLibrary(fds.h)
  -> candidates: []
Using library Arduino_JSON at version 0.1.0 in folder: C:\Users\Usuario\Documents\Arduino\libraries\Arduino_JSON 
Using library ArduinoBLE at version 1.2.1 in folder: C:\Users\Usuario\Documents\Arduino\libraries\ArduinoBLE 
Using library NanoBLEFlashPrefs at version 1.1.0 in folder: C:\Users\Usuario\Documents\Arduino\libraries\NanoBLEFlashPrefs 
Compilation error: Error: 2 UNKNOWN: exit status 1

**Comment by Dirk-** [comment]
This library is for Arduino Nano 33 BLE and Nano 33 BLE Sense, not for the Nano 33 IoT which you seem to use. The former boards are based on the nRF52840 processor from Nordic Semiconductors, the IoT is based on the Arm® Cortex®-M0 32-bit SAMD21.

The SAMD21 also lacks EEPROM, but I use features of the nRF52840 specifically for the replacement.

**Comment by Dirk-** [comment]
You could try this lib: https://github.com/khoih-prog/FlashStorage_SAMD
