### ISSUE TITLE
Modifying a single pref value

### ISSUE THREAD

**Issue by LazaroFilm** [Dirk-/NanoBLEFlashPrefs#6]
**Questions:**
- If I modify a single value in the pref and initiate a write, does it re-write all the values or only the ones that were modified?

- Otherwise, can you create separate struct that contain different prefs and only save one of them?
I'm looking to have one array that is fairly untouched for each device. 

**Why I'm asking the questions:**
I have an array of settings that never changes for a device (Sensor calibrations) but different for each board, so I would rather save it out of the compiled file to push the same file to each during updates while keeping those specific values.
I also have some user defined values (axis selection, zoom value, potentiometer value... that need to be changed fairly frequently to keep them between restarts.
I want to be able to write the user prefs without having to uselessly rewrite the constant calibration settings

**Comment by Dirk-** [comment]
Hi,

answers to your questions:

- The lib rewrites the complete struct.
- So far, the lib only deals with one struct.

I understand your use case, but I like to keep the library as simple as possible. You should probably just try to save everything in one struct and monitor the memory needed with `statusString()`. If you feel the memory gets low, do `deletePrefs()` and `garbageCollection()`.
