### ISSUE TITLE
Example code issue

### ISSUE THREAD

**Issue by Bigshooter** [Dirk-/NanoBLEFlashPrefs#7]
I used your example code and I get the following response.

Read record...
No preferences found. Return code: 10, FDS_ERR_NOT_FOUND

Write preferences...

Read preferences...
Return code: 10, FDS_ERR_NOT_FOUND

Write another preference record...

Read preferences...
Return code: 10, FDS_ERR_NOT_FOUND

Done. Press reset button to see that again.

I then added 

Serial.println(myFlashPrefs.statusString());

after your 5 second wait and got the following additional information

34801 pages available, 1 open records, 9494 valid records, 1 dirty, 241 corruption

Either way it does not seem to save anything?

**Comment by Dirk-** [comment]
Looks like your board already has some records stored by some other code. If you don't need these records, try to delete them:

```
  Serial.println("before");
  Serial.println(myFlashPrefs.statusString());
  int rc = myFlashPrefs.deletePrefs();
  Serial.println(myFlashPrefs.errorString(rc));
  rc = myFlashPrefs.garbageCollection();
  Serial.println(myFlashPrefs.errorString(rc));
  Serial.println("after");
  Serial.println(myFlashPrefs.statusString());
```

The number of available pages seems a bit high. What kind of board do you have, Nano 33 BLE or 33 BLE Sense?

**Comment by Dirk-** [comment]
I hope your problem is fixed now. If not, please take a look at the `NanoBLEFlashPrefsUtils` example sketch in version 1.2 of the library.
